CREATE TABLE `lm_smsmsg` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`phone` VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '手机号',
	`code` VARCHAR(50) NULL DEFAULT NULL COMMENT '验证码',
	`content` VARCHAR(250) NULL DEFAULT NULL COMMENT '内容',
	`expire_time` INT(11) NULL DEFAULT NULL COMMENT '过期时间',
	`create_time` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
	PRIMARY KEY (`id`)
)
COMMENT='短信记录'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=19
;
