CREATE TABLE `smsmsg` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`phone` VARCHAR(50) NOT NULL DEFAULT '0' COMMENT '手机号',
	`code` VARCHAR(50) NULL DEFAULT NULL COMMENT '验证码',
	`content` VARCHAR(250) NULL DEFAULT NULL,
	`create_time` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COMMENT='短信记录'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;